#!/bin/bash

binary=$1
strace=$2
name=$(basename -- "$binary")

apt install -y curl python2 zip unzip strace

ldd ${binary} > ${name}.ldd.out
strace -f -o ${name}.strace.out $2
python2 filefilter.py ${name}.ldd.out ${name}.strace.out > ${name}.file.lst
echo ${binary} >> ${name}.file.lst
cat ${name}.file.lst | zip -@ ${name}.zip
mkdir ${name}_tmp
cd ${name}_tmp
unzip ../${name}.zip
tar cvfz ../${name}.tar.gz *
cd ..
rm -rf  ${name}_tmp ${name}.strace.out ${name}.ldd.out ${name}.zip ${name}.file.lst
echo ""
echo "Output ${name}.tar.gz contents:"
tar tvfz ${name}.tar.gz

